ALTER TYPE "PaymentTypeClassification" ADD VALUE IF NOT EXISTS 'CHECK';
ALTER TYPE "PaymentTypeClassification" ADD VALUE IF NOT EXISTS 'DIGITAL_WALLET';
ALTER TYPE "PaymentTypeClassification" ADD VALUE IF NOT EXISTS 'NON_CASH_SETTLEMENT';
