import {
  AccountNature,
  ChartAccountLevel,
  ChartAccountStatus,
  ChartAccountType,
  DefaultAccountUsageType,
} from '@prisma/client';

export const StandardDefaultChartAccounts = [
  {
    accountCode: '1000000000',
    accountTitle: 'Assets',
    accountLevel: ChartAccountLevel.MAJOR,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 1,
  },
  {
    accountCode: '1010000000',
    parentAccountCode: '1000000000',
    accountTitle: 'Current Assets',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 2,
  },
  {
    accountCode: '1010100000',
    parentAccountCode: '1010000000',
    accountTitle: 'Cash and Cash Equivalents',
    accountLevel: ChartAccountLevel.SUB2,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 3,
  },
  {
    accountCode: '1010101000',
    parentAccountCode: '1010100000',
    accountTitle: 'Cash on Hand',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 4,
  },
  {
    accountCode: '1010101001',
    parentAccountCode: '1010101000',
    accountTitle: 'Cash On Hand',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 5,
  },
  {
    accountCode: '1010101002',
    parentAccountCode: '1010101000',
    accountTitle: 'Petty Cash Fund',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 6,
  },
  {
    accountCode: '1010101003',
    parentAccountCode: '1010101000',
    accountTitle: 'Revolving Fund',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 7,
  },
  {
    accountCode: '1010102000',
    parentAccountCode: '1010100000',
    accountTitle: 'Cash in Banks',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 8,
  },
  {
    accountCode: '1010102001',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - BDO',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 9,
  },
  {
    accountCode: '1010102002',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - BPI',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 10,
  },
  {
    accountCode: '1010102003',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - Metrobank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 11,
  },
  {
    accountCode: '1010102004',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - Landbank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 12,
  },
  {
    accountCode: '1010102005',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - PNB',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 13,
  },
  {
    accountCode: '1010102006',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - SB',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 14,
  },
  {
    accountCode: '1010102007',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - China Bank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 15,
  },
  {
    accountCode: '1010102008',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - UnionBank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 16,
  },
  {
    accountCode: '1010102009',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - RCBC',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 17,
  },
  {
    accountCode: '1010102010',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - EastWest',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 18,
  },
  {
    accountCode: '1010102011',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - DBP',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 19,
  },
  {
    accountCode: '1010102012',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - Philtrust Bank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 20,
  },
  {
    accountCode: '1010102013',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - AUB',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 21,
  },
  {
    accountCode: '1010102014',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - RB',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 22,
  },
  {
    accountCode: '1010102015',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - Maybank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 23,
  },
  {
    accountCode: '1010102016',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - BC',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 24,
  },
  {
    accountCode: '1010102017',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - PBCom',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 25,
  },
  {
    accountCode: '1010102018',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - Maya',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 26,
  },
  {
    accountCode: '1010102019',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - CIMB',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 27,
  },
  {
    accountCode: '1010102020',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - Tonik',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 28,
  },
  {
    accountCode: '1010102021',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - UNO',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 29,
  },
  {
    accountCode: '1010102022',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - GoTyme',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 30,
  },
  {
    accountCode: '1010102023',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - UnionDigital',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 31,
  },
  {
    accountCode: '1010102024',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - BanKo',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 32,
  },
  {
    accountCode: '1010102025',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - PSBank',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 33,
  },
  {
    accountCode: '1010102026',
    parentAccountCode: '1010102000',
    accountTitle: 'Cash in Bank - DiskarTech',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 34,
  },
  {
    accountCode: '1010102900',
    parentAccountCode: '1010102000',
    accountTitle: 'Time Deposit',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 35,
  },
  {
    accountCode: '1010103000',
    parentAccountCode: '1010100000',
    accountTitle: 'Accounts Receivables',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 36,
  },
  {
    accountCode: '1010103001',
    parentAccountCode: '1010103000',
    accountTitle: 'Accounts Receivables - Trade',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 37,
  },
  {
    accountCode: '1010103002',
    parentAccountCode: '1010103000',
    accountTitle: 'Accounts Receivables - Others',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 38,
  },
  {
    accountCode: '1010103003',
    parentAccountCode: '1010103000',
    accountTitle: 'Advances To Suppliers',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 39,
  },
  {
    accountCode: '1010103004',
    parentAccountCode: '1010103000',
    accountTitle: 'Advances To Officers and  Employees',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 40,
  },
  {
    accountCode: '1010103005',
    parentAccountCode: '1010103000',
    accountTitle: 'Other Advances',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 41,
  },
  {
    accountCode: '1010104000',
    parentAccountCode: '1010100000',
    accountTitle: 'Other Current Assets',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 42,
  },
  {
    accountCode: '1010104001',
    parentAccountCode: '1010104000',
    accountTitle: 'Prepaid Expenses',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 43,
  },
  {
    accountCode: '1010104002',
    parentAccountCode: '1010104000',
    accountTitle: 'Bir 2307 - Creditable Withheld Taxes',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 44,
  },
  {
    accountCode: '1010104003',
    parentAccountCode: '1010104000',
    accountTitle: 'Input VAT',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 45,
  },
  {
    accountCode: '1010104004',
    parentAccountCode: '1010104000',
    accountTitle: 'Compensation Witholding Receivables',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 46,
  },
  {
    accountCode: '1010104005',
    parentAccountCode: '1010104000',
    accountTitle: 'Deferred Input Tax',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 47,
  },
  {
    accountCode: '1010104006',
    parentAccountCode: '1010104000',
    accountTitle: 'Tax Credits',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 48,
  },
  {
    accountCode: '1010105000',
    parentAccountCode: '1010100000',
    accountTitle: 'Inventories',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 49,
  },
  {
    accountCode: '1010105001',
    parentAccountCode: '1010105000',
    accountTitle: 'Merchandise Inventory',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 50,
  },
  {
    accountCode: '1010105002',
    parentAccountCode: '1010105000',
    accountTitle: 'Inventory - Intransit',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 51,
  },
  {
    accountCode: '1010105003',
    parentAccountCode: '1010105000',
    accountTitle: 'Inventory - Others',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 52,
  },
  {
    accountCode: '1010105004',
    parentAccountCode: '1010105000',
    accountTitle: 'Inventory Clearing Account',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 53,
  },
  {
    accountCode: '1020000000',
    parentAccountCode: '1000000000',
    accountTitle: 'Non-Current Assets',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 54,
  },
  {
    accountCode: '1020100000',
    parentAccountCode: '1020000000',
    accountTitle: 'Property, Plant and Equipment',
    accountLevel: ChartAccountLevel.SUB2,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 55,
  },
  {
    accountCode: '1020101000',
    parentAccountCode: '1020100000',
    accountTitle: 'Land',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 56,
  },
  {
    accountCode: '1020101001',
    parentAccountCode: '1020101000',
    accountTitle: 'Land',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 57,
  },
  {
    accountCode: '1020101002',
    parentAccountCode: '1020101000',
    accountTitle: 'Accumulated Depreciation - Land',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 58,
  },
  {
    accountCode: '1020102000',
    parentAccountCode: '1020100000',
    accountTitle: 'Building',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 59,
  },
  {
    accountCode: '1020102001',
    parentAccountCode: '1020102000',
    accountTitle: 'Building',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 60,
  },
  {
    accountCode: '1020102002',
    parentAccountCode: '1020102000',
    accountTitle: 'Accumulated Depreciation - Building',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 61,
  },
  {
    accountCode: '1020103000',
    parentAccountCode: '1020100000',
    accountTitle: 'Office Equipment',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 62,
  },
  {
    accountCode: '1020103001',
    parentAccountCode: '1020103000',
    accountTitle: 'Office Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 63,
  },
  {
    accountCode: '1020103002',
    parentAccountCode: '1020103000',
    accountTitle: 'Accumulated Depreciation - Office Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 64,
  },
  {
    accountCode: '1020104000',
    parentAccountCode: '1020100000',
    accountTitle: 'Transportation Equipment',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 65,
  },
  {
    accountCode: '1020104001',
    parentAccountCode: '1020104000',
    accountTitle: 'Transportation Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 66,
  },
  {
    accountCode: '1020104002',
    parentAccountCode: '1020104000',
    accountTitle: 'Accumulated Depreciation - Transportation Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 67,
  },
  {
    accountCode: '1020105000',
    parentAccountCode: '1020100000',
    accountTitle: 'Communication Equipment',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 68,
  },
  {
    accountCode: '1020105001',
    parentAccountCode: '1020105000',
    accountTitle: 'Communication Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 69,
  },
  {
    accountCode: '1020105002',
    parentAccountCode: '1020105000',
    accountTitle: 'Accumulated Depreciation - Communication Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 70,
  },
  {
    accountCode: '1020106000',
    parentAccountCode: '1020100000',
    accountTitle: 'Furniture and Fixtures',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 71,
  },
  {
    accountCode: '1020106001',
    parentAccountCode: '1020106000',
    accountTitle: 'Furniture and Fixtures',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 72,
  },
  {
    accountCode: '1020106002',
    parentAccountCode: '1020106000',
    accountTitle: 'Accumulated Depreciation - Furniture and Fixtures',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 73,
  },
  {
    accountCode: '1020107000',
    parentAccountCode: '1020100000',
    accountTitle: 'Billboards and Signages',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 74,
  },
  {
    accountCode: '1020107001',
    parentAccountCode: '1020107000',
    accountTitle: 'Billboards',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 75,
  },
  {
    accountCode: '1020107002',
    parentAccountCode: '1020107000',
    accountTitle: 'Signages',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 76,
  },
  {
    accountCode: '1020107003',
    parentAccountCode: '1020107000',
    accountTitle: 'Accumulated Depreciation - Billboards and Signages',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 77,
  },
  {
    accountCode: '1020108000',
    parentAccountCode: '1020100000',
    accountTitle: 'Leasehold Improvements',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 78,
  },
  {
    accountCode: '1020108001',
    parentAccountCode: '1020108000',
    accountTitle: 'Leasehold Improvements',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 79,
  },
  {
    accountCode: '1020108002',
    parentAccountCode: '1020108000',
    accountTitle: 'Accumulated Depreciation - Leasehold Improvements',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.ASSET,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 80,
  },
  {
    accountCode: '2000000000',
    accountTitle: 'Liabilities',
    accountLevel: ChartAccountLevel.MAJOR,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 81,
  },
  {
    accountCode: '2010000000',
    parentAccountCode: '2000000000',
    accountTitle: 'Current Liabilities',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 82,
  },
  {
    accountCode: '2010001000',
    parentAccountCode: '2010000000',
    accountTitle: 'Accounts Payables',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 83,
  },
  {
    accountCode: '2010001001',
    parentAccountCode: '2010001000',
    accountTitle: 'Accounts Payable - Trade',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 84,
  },
  {
    accountCode: '2010001002',
    parentAccountCode: '2010001000',
    accountTitle: 'Accounts Payable - Others',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 85,
  },
  {
    accountCode: '2010001003',
    parentAccountCode: '2010001000',
    accountTitle: 'SSS Contributions Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 86,
  },
  {
    accountCode: '2010001004',
    parentAccountCode: '2010001000',
    accountTitle: 'HDMF Contributions Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 87,
  },
  {
    accountCode: '2010001005',
    parentAccountCode: '2010001000',
    accountTitle: 'PHIC Contributions Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 88,
  },
  {
    accountCode: '2010002000',
    parentAccountCode: '2010000000',
    accountTitle: 'Taxes Payables',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 89,
  },
  {
    accountCode: '2010002001',
    parentAccountCode: '2010002000',
    accountTitle: 'CWT - Witholding Tax Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 90,
  },
  {
    accountCode: '2010002002',
    parentAccountCode: '2010002000',
    accountTitle: 'EWT - Witholding Tax Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 91,
  },
  {
    accountCode: '2010002003',
    parentAccountCode: '2010002000',
    accountTitle: 'Final - Withholding Tax Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 92,
  },
  {
    accountCode: '2010002004',
    parentAccountCode: '2010002000',
    accountTitle: 'Deferred Output VAT',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 93,
  },
  {
    accountCode: '2010002005',
    parentAccountCode: '2010002000',
    accountTitle: 'Output VAT',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 94,
  },
  {
    accountCode: '2010002006',
    parentAccountCode: '2010002000',
    accountTitle: 'VAT Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 95,
  },
  {
    accountCode: '2010002007',
    parentAccountCode: '2010002000',
    accountTitle: 'Income Tax Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 96,
  },
  {
    accountCode: '2010002008',
    parentAccountCode: '2010002000',
    accountTitle: 'Other Taxes Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 97,
  },
  {
    accountCode: '2010003000',
    parentAccountCode: '2010000000',
    accountTitle: 'Shor-Term Loans Payable',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 98,
  },
  {
    accountCode: '2010003001',
    parentAccountCode: '2010003000',
    accountTitle: 'Bank Loans Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 99,
  },
  {
    accountCode: '2010003002',
    parentAccountCode: '2010003000',
    accountTitle: 'Mortgage Loan Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 100,
  },
  {
    accountCode: '2010004000',
    parentAccountCode: '2010000000',
    accountTitle: 'Other Current Liabilities',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 101,
  },
  {
    accountCode: '2010004001',
    parentAccountCode: '2010004000',
    accountTitle: 'Other Payables',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 102,
  },
  {
    accountCode: '2010004002',
    parentAccountCode: '2010004000',
    accountTitle: 'Accrued Expenses',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 103,
  },
  {
    accountCode: '2010004003',
    parentAccountCode: '2010004000',
    accountTitle: 'Dividends Payable',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 104,
  },
  {
    accountCode: '2020000000',
    parentAccountCode: '2000000000',
    accountTitle: 'Non Current Liabilities',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 105,
  },
  {
    accountCode: '2020001000',
    parentAccountCode: '2020000000',
    accountTitle: 'Long-Term Debt',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.LIABILITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 106,
  },
  {
    accountCode: '3000000000',
    accountTitle: 'Equity',
    accountLevel: ChartAccountLevel.MAJOR,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 107,
  },
  {
    accountCode: '3010000000',
    parentAccountCode: '3000000000',
    accountTitle: "Shareholders' Equity",
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 108,
  },
  {
    accountCode: '3011000000',
    parentAccountCode: '3000000000',
    accountTitle: 'Capital Stock',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 109,
  },
  {
    accountCode: '3010100000',
    parentAccountCode: '3010000000',
    accountTitle: 'Share Capital',
    accountLevel: ChartAccountLevel.SUB2,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 110,
  },
  {
    accountCode: '3010100001',
    parentAccountCode: '3010100000',
    accountTitle: 'Ordinary Share Capital',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 111,
  },
  {
    accountCode: '3010100002',
    parentAccountCode: '3010100000',
    accountTitle: 'Share Premium',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 112,
  },
  {
    accountCode: '3010200000',
    parentAccountCode: '3010000000',
    accountTitle: 'Retained Earnings',
    accountLevel: ChartAccountLevel.SUB2,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 113,
  },
  {
    accountCode: '3010200001',
    parentAccountCode: '3010200000',
    accountTitle: 'Retained Earnings - Current',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 114,
  },
  {
    accountCode: '3010200002',
    parentAccountCode: '3010200000',
    accountTitle: 'Unappropriated Retained Earnings',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 115,
  },
  {
    accountCode: '3010200003',
    parentAccountCode: '3010200000',
    accountTitle: 'Appropriated Retained Earnings',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 116,
  },
  {
    accountCode: '3010300000',
    parentAccountCode: '3010000000',
    accountTitle: 'Reserves',
    accountLevel: ChartAccountLevel.SUB2,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 117,
  },
  {
    accountCode: '3010300001',
    parentAccountCode: '3010300000',
    accountTitle: 'Reserves',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 118,
  },
  {
    accountCode: '3010400000',
    parentAccountCode: '3010000000',
    accountTitle: 'Treasury Shares',
    accountLevel: ChartAccountLevel.SUB2,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    orderNo: 119,
  },
  {
    accountCode: '3010400001',
    parentAccountCode: '3010400000',
    accountTitle: 'Treasury Shares',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 120,
  },
  {
    accountCode: '3010400002',
    parentAccountCode: '3010400000',
    accountTitle: 'Treasury Stock',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EQUITY,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Balance Sheet',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 121,
  },
  {
    accountCode: '4000000000',
    accountTitle: 'Revenues',
    accountLevel: ChartAccountLevel.MAJOR,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 122,
  },
  {
    accountCode: '4010000000',
    parentAccountCode: '4000000000',
    accountTitle: 'Sales',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 123,
  },
  {
    accountCode: '4010000001',
    parentAccountCode: '4010000000',
    accountTitle: 'VAT Sales',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 124,
  },
  {
    accountCode: '4010000002',
    parentAccountCode: '4010000000',
    accountTitle: 'Zero Rated Sales',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 125,
  },
  {
    accountCode: '4010000003',
    parentAccountCode: '4010000000',
    accountTitle: 'Sales Discount',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 126,
  },
  {
    accountCode: '4010000004',
    parentAccountCode: '4010000000',
    accountTitle: 'Sales Returns',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 127,
  },
  {
    accountCode: '4020000000',
    parentAccountCode: '4000000000',
    accountTitle: 'Service Revenues',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 128,
  },
  {
    accountCode: '4020000001',
    parentAccountCode: '4020000000',
    accountTitle: 'Service Fees',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 129,
  },
  {
    accountCode: '5000000000',
    accountTitle: 'Cost of Sales/Services',
    accountLevel: ChartAccountLevel.MAJOR,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 130,
  },
  {
    accountCode: '5000001000',
    parentAccountCode: '5000000000',
    accountTitle: 'Cost of Sales',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 131,
  },
  {
    accountCode: '5000002000',
    parentAccountCode: '5000000000',
    accountTitle: 'Cost of Services',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.REVENUE,
    accountNature: AccountNature.CREDIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 132,
  },
  {
    accountCode: '6000000000',
    accountTitle: 'Operating Expenses',
    accountLevel: ChartAccountLevel.MAJOR,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 133,
  },
  {
    accountCode: '6010000000',
    parentAccountCode: '6000000000',
    accountTitle: 'Administrative Expenses',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 134,
  },
  {
    accountCode: '6010000001',
    parentAccountCode: '6010000000',
    accountTitle: 'Salaries and Wages',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 135,
  },
  {
    accountCode: '6010000002',
    parentAccountCode: '6010000000',
    accountTitle: '13th Month Pay',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 136,
  },
  {
    accountCode: '6010000003',
    parentAccountCode: '6010000000',
    accountTitle: 'Bonuses',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 137,
  },
  {
    accountCode: '6010000004',
    parentAccountCode: '6010000000',
    accountTitle: 'SSS/HDMF/PHIC Contributions',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 138,
  },
  {
    accountCode: '6010000005',
    parentAccountCode: '6010000000',
    accountTitle: "Employees' Benefits",
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 139,
  },
  {
    accountCode: '6010000006',
    parentAccountCode: '6010000000',
    accountTitle: 'Employee Relations',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 140,
  },
  {
    accountCode: '6010000007',
    parentAccountCode: '6010000000',
    accountTitle: 'Trainings and Seminars',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 141,
  },
  {
    accountCode: '6010000008',
    parentAccountCode: '6010000000',
    accountTitle: 'Transportation and Travel',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 142,
  },
  {
    accountCode: '6010000020',
    parentAccountCode: '6010000000',
    accountTitle: 'Telephone and Communication',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 143,
  },
  {
    accountCode: '6010000022',
    parentAccountCode: '6010000000',
    accountTitle: 'Representation Expense',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 144,
  },
  {
    accountCode: '6010000021',
    parentAccountCode: '6010000000',
    accountTitle: 'Rent Expense',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 145,
  },
  {
    accountCode: '6010000026',
    parentAccountCode: '6010000000',
    accountTitle: 'Electricity',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 146,
  },
  {
    accountCode: '6010000023',
    parentAccountCode: '6010000000',
    accountTitle: 'Water',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 147,
  },
  {
    accountCode: '6010000024',
    parentAccountCode: '6010000000',
    accountTitle: 'Fuel and Oil',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 148,
  },
  {
    accountCode: '6010000025',
    parentAccountCode: '6010000000',
    accountTitle: 'Repairs and Maintenance',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 149,
  },
  {
    accountCode: '6010000035',
    parentAccountCode: '6010000000',
    accountTitle: 'Professional Fees',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 150,
  },
  {
    accountCode: '6010000036',
    parentAccountCode: '6010000000',
    accountTitle: 'Insurance Expense',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 151,
  },
  {
    accountCode: '6010000037',
    parentAccountCode: '6010000000',
    accountTitle: 'Taxes and Licenses',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 152,
  },
  {
    accountCode: '6010000045',
    parentAccountCode: '6010000000',
    accountTitle: 'Depreciation Expense',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 153,
  },
  {
    accountCode: '6010000046',
    parentAccountCode: '6010000000',
    accountTitle: 'Audit Fees',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 154,
  },
  {
    accountCode: '6020000000',
    parentAccountCode: '6000000000',
    accountTitle: 'Marketing and Sales Expense',
    accountLevel: ChartAccountLevel.SUB1,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 155,
  },
  {
    accountCode: '6020000001',
    parentAccountCode: '6020000000',
    accountTitle: 'Advertising Expenses',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 156,
  },
  {
    accountCode: '6020000002',
    parentAccountCode: '6020000000',
    accountTitle: 'Promotion Expenses',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 157,
  },
  {
    accountCode: '6020000005',
    parentAccountCode: '6020000000',
    accountTitle: 'Commission Expense',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 158,
  },
  {
    accountCode: '6020000003',
    parentAccountCode: '6020000000',
    accountTitle: 'Marketing Collaterals',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 159,
  },
  {
    accountCode: '6020000004',
    parentAccountCode: '6020000000',
    accountTitle: 'POP Materials',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 160,
  },
  {
    accountCode: '6020001000',
    parentAccountCode: '6020000000',
    accountTitle: 'Depreciation Expense - Property, Plant and Equipment',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 161,
  },
  {
    accountCode: '6020001001',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense Land',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 162,
  },
  {
    accountCode: '6020001002',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Building',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 163,
  },
  {
    accountCode: '6020001003',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Office Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 164,
  },
  {
    accountCode: '6020001004',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Transportation Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 165,
  },
  {
    accountCode: '6020001005',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Communication Equipment',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 166,
  },
  {
    accountCode: '6020001006',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Furniture and Fixtures',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 167,
  },
  {
    accountCode: '6020001007',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Billboards and Signages',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 168,
  },
  {
    accountCode: '6020001008',
    parentAccountCode: '6020001000',
    accountTitle: 'Depreciation Expense - Leasehold Improvements',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 169,
  },
  {
    accountCode: '6800000000',
    parentAccountCode: '6000000000',
    accountTitle: 'Other Income',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 170,
  },
  {
    accountCode: '6800001000',
    parentAccountCode: '6800000000',
    accountTitle: 'Incentive Commision Income',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 171,
  },
  {
    accountCode: '6800002000',
    parentAccountCode: '6800000000',
    accountTitle: 'Interest on Savings Deposits',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 172,
  },
  {
    accountCode: '6900000000',
    parentAccountCode: '6000000000',
    accountTitle: 'Other Expenses',
    accountLevel: ChartAccountLevel.SUB3,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    orderNo: 173,
  },
  {
    accountCode: '6900001000',
    parentAccountCode: '6900000000',
    accountTitle: 'Interest On Loans',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 174,
  },
  {
    accountCode: '6900002000',
    parentAccountCode: '6900000000',
    accountTitle: 'Financing Cost',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 175,
  },
  {
    accountCode: '6900003000',
    parentAccountCode: '6900000000',
    accountTitle: 'Penalties & Surcharges',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 176,
  },
  {
    accountCode: '6900004000',
    parentAccountCode: '6900000000',
    accountTitle: 'Bank Charges',
    accountLevel: ChartAccountLevel.SPECIFIC,
    accountType: ChartAccountType.EXPENSE,
    accountNature: AccountNature.DEBIT,
    accountGroup: null,
    statementSection: 'Income Statement',
    reportAlias: null,
    isPostingAccount: true,
    orderNo: 177,
  },
] as const;

export const StandardDefaultAccountMappings = [
  {
    moduleCode: 'BM',
    accountRole: 'CASH_IN_BANK_PARENT',
    accountCode: '1010102000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Bank Masterfile generated Cash in Bank accounts.',
  },
  {
    moduleCode: 'BM',
    accountRole: 'CASH_ON_HAND_PARENT',
    accountCode: '1010101000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Cash on Hand account group reference.',
  },
  {
    moduleCode: 'CD',
    accountRole: 'PETTY_CASH_FUND',
    accountCode: '1010101002',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default petty cash fund posting account.',
  },
  {
    moduleCode: 'CD',
    accountRole: 'ACCOUNTS_PAYABLE_PARENT',
    accountCode: '2010001000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Accounts payable group for supplier payment debit choices.',
  },
] as const;

export const ActiveDefaultCoaStatus = ChartAccountStatus.ACTIVE;

