import { SystemGeneratedAuditLabel } from '../../../../common/utils/audit-user.util';
import type { ServiceInvoiceWithDetails } from '../types/service-invoice-with-details.type';

export function mapServiceInvoice(invoice: ServiceInvoiceWithDetails, userNames: Map<number, string>) {
  return {
    id: invoice.id.toString(),
    transactionNo: invoice.transactionNo,
    documentDate: toDateValue(invoice.documentDate),
    dueDate: toDateValue(invoice.dueDate),
    invoiceNo: invoice.invoiceNo ?? null,
    referenceNo: invoice.referenceNo ?? null,
    partyId: invoice.partyId?.toString() ?? null,
    customerCode: invoice.partyCodeSnapshot,
    customerName: invoice.partyNameSnapshot,
    billToName: invoice.billToNameSnapshot ?? null,
    address: invoice.addressSnapshot ?? null,
    contactPerson: invoice.contactPersonSnapshot ?? null,
    contactNo: invoice.contactNoSnapshot ?? null,
    businessStyle: invoice.businessStyle ?? null,
    projectCode: invoice.projectCode ?? null,
    projectName: invoice.projectName ?? null,
    projectRef: invoice.projectRef ?? null,
    salesAssociate: invoice.salesAssociate ?? null,
    teamAssigned: invoice.teamAssigned ?? null,
    currency: invoice.currencyCode,
    exchangeRate: Number(invoice.exchangeRate),
    netAmount: Number(invoice.netAmount),
    vatAmount: Number(invoice.vatAmount),
    wvatAmount: Number(invoice.wvatAmount),
    ewtAmount: Number(invoice.ewtAmount),
    discountAmount: Number(invoice.discountAmount),
    grossAmount: Number(invoice.grossAmount),
    termId: invoice.termId?.toString() ?? null,
    terms: invoice.term?.name ?? null,
    receivableAccountId: invoice.receivableAccountId?.toString() ?? '',
    receivableAccountCode: invoice.receivableAccount?.accountCode ?? invoice.journalEntries[0]?.accountCodeSnapshot ?? '',
    receivableAccountTitle: invoice.receivableAccount?.accountTitle ?? invoice.journalEntries[0]?.accountTitleSnapshot ?? '',
    remarks: invoice.remarks ?? null,
    status: invoice.status,
    details: invoice.details.map((detail) => ({
      id: detail.id.toString(),
      companyId: detail.companyId,
      branchUnitId: detail.branchUnitId,
      lineNumber: detail.lineNumber,
      description: detail.description,
      particulars: detail.particulars ?? null,
      quantity: Number(detail.quantity),
      amount: Number(detail.amount),
      netAmount: Number(detail.netAmount),
      vatAmount: Number(detail.vatAmount),
      wvatAmount: Number(detail.wvatAmount),
      ewtAmount: Number(detail.ewtAmount),
      discountPercent: Number(detail.discountPercent),
      discountAmount: Number(detail.discountAmount),
      grossAmount: Number(detail.grossAmount),
      vatType: detail.vatType ?? null,
      vatable: detail.vatable,
      vatInclusive: detail.vatInclusive,
      withWvat: detail.withWvat,
      wvatType: detail.wvatType ?? null,
      withEwt: detail.withEwt,
      ewtType: detail.ewtType ?? null,
      responsibilityCenterId: detail.responsibilityCenterId?.toString() ?? null,
      responsibilityCenter: detail.responsibilityCenterSnapshot ?? null,
    })),
    journalEntries: invoice.journalEntries.map((entry) => ({
      id: entry.id.toString(),
      referenceType: entry.referenceType,
      referenceId: entry.referenceId.toString(),
      lineNumber: entry.lineNumber,
      accountId: entry.accountId?.toString() ?? '',
      accountCode: entry.accountCodeSnapshot,
      accountTitle: entry.accountTitleSnapshot,
      currencyCode: entry.currencyCode,
      exchangeRate: Number(entry.exchangeRate),
      particulars: entry.particulars ?? null,
      debit: Number(entry.debit),
      credit: Number(entry.credit),
      vatType: entry.vatType ?? null,
      atcCode: entry.atcCode ?? null,
      partyCode: entry.partyCodeSnapshot ?? null,
      partyName: entry.partyNameSnapshot ?? null,
      responsibilityCenterId: entry.responsibilityCenterId?.toString() ?? null,
      responsibilityCenter: entry.responsibilityCenterSnapshot ?? null,
      refNo: entry.refNo ?? null,
    })),
    createdBy: invoice.createdByUserId === null ? SystemGeneratedAuditLabel : (userNames.get(invoice.createdByUserId) ?? null),
    createdAt: invoice.createdAt.toISOString(),
    updatedBy: (invoice.updatedByUserId && userNames.get(invoice.updatedByUserId)) ?? null,
    updatedAt: invoice.updatedAt.toISOString(),
  };
}

function toDateValue(date: Date) {
  return date.toISOString().slice(0, 10);
}
