import { mapCashVoucher } from './cash-voucher.mapper';
import type { CashVoucherWithDetails } from '../types/cash-voucher-with-details.type';

describe('mapCashVoucher', () => {
  it('maps snapshots and calculates taxable gross and disbursement amounts', () => {
    const voucher = {
      id: 41n,
      branchUnitId: 7,
      voucherNo: 'CV-0001',
      voucherDate: new Date('2026-09-01T00:00:00.000Z'),
      paymentDueDate: null,
      referenceNo: null,
      referenceModule: null,
      voucherReferenceNo: null,
      invoiceReferenceNo: null,
      paymentMethod: 'CASH',
      disbursementType: null,
      partyId: 9n,
      partyCodeSnapshot: 'V-001',
      partyNameSnapshot: 'Vendor One',
      creditAccountId: null,
      projectCode: null,
      projectName: null,
      preparedBy: 'Preparer',
      currencyCode: 'PHP',
      exchangeRate: 1,
      amount: 100,
      remarks: null,
      status: 'DRAFT',
      createdByUserId: null,
      createdAt: new Date('2026-09-01T00:00:00.000Z'),
      updatedByUserId: null,
      updatedAt: null,
      party: null,
      creditAccount: null,
      details: [
        {
          id: 1n,
          lineNumber: 1,
          accountId: 2n,
          accountCodeSnapshot: '6100',
          accountTitleSnapshot: 'Expense',
          particulars: 'Supplies',
          remarks: null,
          debit: 100,
          credit: 0,
          grossAmount: 100,
          netAmount: 100,
          vatType: 'VAT',
          vatCode: 'V',
          vatPercent: 12,
          vatAmount: 0,
          ewtCode: 'EWT',
          ewtPercent: 2,
          ewtAmount: 0,
          disburseAmount: 100,
          partyId: null,
          partyCodeSnapshot: null,
          partyNameSnapshot: null,
          responsibilityCenterId: null,
          responsibilityCenterSnapshot: null,
          refId: null,
          checkDate: null,
          checkNo: null,
          checkStatus: null,
          account: null,
          party: null,
          responsibilityCenter: null,
        },
        {
          id: 2n,
          lineNumber: 2,
          accountId: null,
          accountCodeSnapshot: null,
          accountTitleSnapshot: 'Input VAT',
          particulars: null,
          remarks: null,
          debit: 13.64,
          credit: 0,
          grossAmount: 13.64,
          netAmount: 0,
          vatType: null,
          vatCode: null,
          vatPercent: 0,
          vatAmount: 0,
          ewtCode: null,
          ewtPercent: 0,
          ewtAmount: 0,
          disburseAmount: 13.64,
          partyId: null,
          partyCodeSnapshot: null,
          partyNameSnapshot: null,
          responsibilityCenterId: null,
          responsibilityCenterSnapshot: null,
          refId: null,
          checkDate: null,
          checkNo: null,
          checkStatus: null,
          account: null,
          party: null,
          responsibilityCenter: null,
        },
      ],
      journalEntries: [],
    } as unknown as CashVoucherWithDetails;

    const result = mapCashVoucher(voucher, new Map());

    expect(result.partyCode).toBe('V-001');
    expect(result.dueDate).toBe('2026-09-01');
    expect(result.amount).toBe(113.64);
    expect(result.disburseAmount).toBe(111.36);
    expect(result.createdBy).toBe('System Generated');
    expect(result.details).toHaveLength(2);
  });
});
