import { ChartAccountLevel, DefaultAccountUsageType } from '@prisma/client';

export const StandardDefaultAccountMappings = [
  {
    moduleCode: 'BM',
    accountRole: 'CASH_IN_BANK_PARENT',
    accountCode: '1010102000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Bank Masterfile generated Cash in Bank accounts.',
  },
  {
    moduleCode: 'BM',
    accountRole: 'CASH_ON_HAND_PARENT',
    accountCode: '1010101000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Cash on Hand account group reference.',
  },
  {
    moduleCode: 'CD',
    accountRole: 'PETTY_CASH_FUND',
    accountCode: '1010101002',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default petty cash fund posting account.',
  },
  {
    moduleCode: 'CD',
    accountRole: 'ACCOUNTS_PAYABLE_PARENT',
    accountCode: '2010001000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Accounts payable group for supplier payment debit choices.',
  },
  {
    moduleCode: 'DA',
    accountRole: 'EXPENSE_PARENT',
    accountCode: '6010000000',
    requiredLevel: ChartAccountLevel.SUB1,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Default Account generated expense accounts.',
  },
  {
    moduleCode: 'DA',
    accountRole: 'REVENUE_PARENT',
    accountCode: '4020000000',
    requiredLevel: ChartAccountLevel.SUB1,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Default Account generated collection revenue accounts.',
  },
  {
    moduleCode: 'DA',
    accountRole: 'FIXED_ASSET_PARENT',
    accountCode: '1020100000',
    requiredLevel: ChartAccountLevel.SUB2,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Default Account generated fixed asset accounts.',
  },
  {
    moduleCode: 'DA',
    accountRole: 'ACCUMULATED_DEPRECIATION_PARENT',
    accountCode: '1020100000',
    requiredLevel: ChartAccountLevel.SUB2,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Default Account generated accumulated depreciation accounts.',
  },
  {
    moduleCode: 'DA',
    accountRole: 'DEPRECIATION_EXPENSE_PARENT',
    accountCode: '6030000000',
    requiredLevel: ChartAccountLevel.SUB1,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Default Account generated depreciation expense accounts.',
  },
  {
    moduleCode: 'DSM',
    accountRole: 'SALES_DISCOUNT_PARENT',
    accountCode: '4010001000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Parent for Discount Management generated sales discount accounts.',
  },
  {
    moduleCode: 'DSM',
    accountRole: 'PURCHASE_DISCOUNT_PARENT',
    accountCode: '5000003000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Parent for Discount Management generated purchase discount accounts.',
  },
  {
    moduleCode: 'IC',
    accountRole: 'INVENTORY_PARENT',
    accountCode: '1010105100',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Item Category generated inventory accounts.',
  },
  {
    moduleCode: 'IC',
    accountRole: 'SALES_PARENT',
    accountCode: '4010002000',
    requiredLevel: ChartAccountLevel.SUB2,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Item Category generated sales accounts.',
  },
  {
    moduleCode: 'IC',
    accountRole: 'COST_OF_SALES_PARENT',
    accountCode: '5000001100',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Item Category generated cost of sales accounts.',
  },
  {
    moduleCode: 'IC',
    accountRole: 'EXPENSE_PARENT',
    accountCode: '6000001000',
    requiredLevel: ChartAccountLevel.SUB1,
    usageType: DefaultAccountUsageType.PARENT,
    description: 'Parent for Item Category generated expense accounts.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'ACCOUNTS_RECEIVABLE_GROUP',
    accountCode: '1010103000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Accounts receivable group for Party Management customer and advance choices.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'ACCOUNTS_PAYABLE_GROUP',
    accountCode: '2010001000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Accounts payable group for Party Management vendor payable choices.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'OTHER_CURRENT_LIABILITIES_GROUP',
    accountCode: '2010004000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Other current liabilities group for Party Management advance/payable choices.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'DEFAULT_RECEIVABLE_ACCOUNT',
    accountCode: '1010103001',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default receivable account for customer parties.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'CUSTOMER_ADVANCE_ACCOUNT',
    accountCode: '2010004004',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default customer advance account for customer parties.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'DEFAULT_PAYABLE_ACCOUNT',
    accountCode: '2010001001',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default payable account for vendor parties.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'VENDOR_ADVANCE_ACCOUNT',
    accountCode: '1010103003',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default vendor advance account for vendor parties.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'EMPLOYEE_ADVANCE_ACCOUNT',
    accountCode: '1010103004',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default employee advance account for employee parties.',
  },
  {
    moduleCode: 'PM',
    accountRole: 'EMPLOYEE_PAYABLE_ACCOUNT',
    accountCode: '2010004005',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default employee payable account for employee parties.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'TAXES_PAYABLES_GROUP',
    accountCode: '2010002000',
    requiredLevel: ChartAccountLevel.SUB3,
    usageType: DefaultAccountUsageType.SELECTION_GROUP,
    description: 'Taxes payable group for Tax Maintenance account choices.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'INPUT_TAX_ACCOUNT',
    accountCode: '2010002011',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default input tax account for VAT tax maintenance.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'OUTPUT_VAT_ACCOUNT',
    accountCode: '2010002005',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default output VAT account for Tax Maintenance.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'DEFERRED_VAT_ACCOUNT',
    accountCode: '2010002004',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default deferred VAT account for Tax Maintenance.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'EXPANDED_WITHHOLDING_TAX_ACCOUNT',
    accountCode: '2010002002',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default expanded withholding tax account for Tax Maintenance.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'CREDITABLE_WITHHOLDING_TAX_ACCOUNT',
    accountCode: '2010002001',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default creditable withholding tax account for Tax Maintenance.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'WITHHOLDING_VATABLE_TAX_ACCOUNT',
    accountCode: '2010002009',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default withholding vatable tax account for Tax Maintenance.',
  },
  {
    moduleCode: 'TXM',
    accountRole: 'FINAL_WITHHOLDING_TAX_ACCOUNT',
    accountCode: '2010002003',
    requiredLevel: ChartAccountLevel.SPECIFIC,
    usageType: DefaultAccountUsageType.POSTING,
    description: 'Default final withholding tax account for Tax Maintenance.',
  },
] as const;
