import { SystemGeneratedAuditLabel } from '../../../../common/utils/audit-user.util';
import type { CollectionReceiptWithDetails } from '../types/collection-receipt-with-details.type';

export function mapCollectionReceipt(receipt: CollectionReceiptWithDetails, userNames: Map<number, string>) {
  return {
    id: receipt.id.toString(),
    transactionNo: receipt.transactionNo,
    documentDate: toDateValue(receipt.documentDate),
    dueDate: toDateValue(receipt.dueDate),
    receiptNo: receipt.receiptNo ?? null,
    referenceNo: receipt.referenceNo ?? null,
    partyId: receipt.partyId?.toString() ?? null,
    customerCode: receipt.partyCodeSnapshot,
    customerName: receipt.partyNameSnapshot,
    billToName: receipt.billToNameSnapshot ?? null,
    paymentId: receipt.paymentId?.toString() ?? null,
    paymentType: receipt.payment?.name ?? null,
    currency: receipt.currencyCode,
    exchangeRate: Number(receipt.exchangeRate),
    netAmount: Number(receipt.netAmount),
    vatAmount: Number(receipt.vatAmount),
    wvatAmount: Number(receipt.wvatAmount),
    ewtAmount: Number(receipt.ewtAmount),
    discountAmount: Number(receipt.discountAmount),
    grossAmount: Number(receipt.grossAmount),
    receivableAccountId: receipt.receivableAccountId?.toString() ?? '',
    receivableAccountCode: receipt.receivableAccount?.accountCode ?? receipt.journalEntries[0]?.accountCodeSnapshot ?? '',
    receivableAccountTitle: receipt.receivableAccount?.accountTitle ?? receipt.journalEntries[0]?.accountTitleSnapshot ?? '',
    remarks: receipt.remarks ?? null,
    status: receipt.status,
    details: receipt.details.map((detail) => ({
      id: detail.id.toString(),
      companyId: detail.companyId,
      branchUnitId: detail.branchUnitId,
      lineNumber: detail.lineNumber,
      description: detail.description,
      partyCode: detail.partyCodeSnapshot ?? null,
      partyName: detail.partyNameSnapshot ?? null,
      particulars: detail.particulars ?? null,
      referenceNo: detail.referenceNo ?? null,
      responsibilityCenterId: detail.responsibilityCenterId?.toString() ?? null,
      responsibilityCenter: detail.responsibilityCenterSnapshot ?? null,
      vatType: detail.vatType ?? null,
      vatPercent: Number(detail.vatPercent),
      cwtCode: detail.cwtCode ?? null,
      cwtPercent: Number(detail.cwtPercent),
      netAmount: Number(detail.netAmount),
      vatAmount: Number(detail.vatAmount),
      ewtAmount: Number(detail.ewtAmount),
      grossAmount: Number(detail.grossAmount),
      totalReceived: Number(detail.totalReceived),
    })),
    journalEntries: receipt.journalEntries.map((entry) => ({
      id: entry.id.toString(),
      referenceType: entry.referenceType,
      referenceId: entry.referenceId.toString(),
      lineNumber: entry.lineNumber,
      accountId: entry.accountId?.toString() ?? '',
      accountCode: entry.accountCodeSnapshot,
      accountTitle: entry.accountTitleSnapshot,
      currencyCode: entry.currencyCode,
      exchangeRate: Number(entry.exchangeRate),
      particulars: entry.particulars ?? null,
      debit: Number(entry.debit),
      credit: Number(entry.credit),
      vatType: entry.vatType ?? null,
      atcCode: entry.atcCode ?? null,
      partyCode: entry.partyCodeSnapshot ?? null,
      partyName: entry.partyNameSnapshot ?? null,
      responsibilityCenterId: entry.responsibilityCenterId?.toString() ?? null,
      responsibilityCenter: entry.responsibilityCenterSnapshot ?? null,
      refNo: entry.refNo ?? null,
    })),
    createdBy: receipt.createdByUserId === null ? SystemGeneratedAuditLabel : (userNames.get(receipt.createdByUserId) ?? null),
    createdAt: receipt.createdAt.toISOString(),
    updatedBy: (receipt.updatedByUserId && userNames.get(receipt.updatedByUserId)) ?? null,
    updatedAt: receipt.updatedAt.toISOString(),
  };
}

function toDateValue(date: Date) {
  return date.toISOString().slice(0, 10);
}
