import { defineAiModuleProfiles } from './profile.helpers';

export const SalesProfiles = defineAiModuleProfiles([
  {
    moduleCode: 'DM',
    name: 'Debit Memo',
    area: 'Sales',
    aliases: ['debit memos', 'customer debit adjustment'],
    summary: 'Records supported debit adjustments to customer accounts.',
  },
  {
    moduleCode: 'CM',
    name: 'Credit Memo',
    area: 'Sales',
    aliases: ['credit memos', 'customer credit adjustment'],
    summary: 'Records supported credit adjustments to customer accounts.',
  },
  {
    moduleCode: 'SQ',
    name: 'Sales Quotation',
    area: 'Sales',
    aliases: ['sales quote', 'customer quotation'],
    summary: 'Prepares quotations for goods offered to customers before an order or sale.',
  },
  {
    moduleCode: 'SQS',
    name: 'Service Quotation',
    area: 'Sales',
    aliases: ['service quote', 'sales quotation services'],
    summary: 'Prepares quotations for services offered to customers.',
  },
  {
    moduleCode: 'SO',
    name: 'Sales Order',
    area: 'Sales',
    aliases: ['sales orders', 'customer order'],
    summary: 'Records customer orders for goods before fulfillment and invoicing.',
  },
  {
    moduleCode: 'SI',
    name: 'Sales Invoice',
    area: 'Sales',
    aliases: ['sales invoices', 'customer invoice'],
    summary: 'Bills customers for delivered goods or completed supported sales transactions.',
  },
  {
    moduleCode: 'B',
    name: 'Billing',
    area: 'Sales',
    aliases: ['customer billing', 'billing records'],
    summary: 'Manages supported customer billing records and billing activity.',
  },
  {
    moduleCode: 'BS',
    name: 'Billing Statement',
    area: 'Sales',
    aliases: ['billing statements', 'customer billing statement'],
    summary: 'Generates statements that summarize supported customer billing activity.',
  },
  {
    moduleCode: 'BI',
    name: 'Billing Invoice',
    area: 'Sales',
    aliases: ['billing invoices'],
    summary: 'Creates invoices from supported customer billing records.',
  },
  {
    moduleCode: 'SVI',
    name: 'Service Invoice',
    area: 'Sales',
    aliases: ['service invoices'],
    summary: 'Bills customers for services rendered by the company.',
  },
  {
    moduleCode: 'CSI',
    name: 'Cash Sales Invoice',
    area: 'Sales',
    aliases: ['cash sales invoices', 'cash sale invoice'],
    summary: 'Records invoices for sales paid at the time of the transaction.',
  },
  {
    moduleCode: 'SJ',
    name: 'Sales Journal',
    area: 'Sales',
    aliases: ['sales journals'],
    summary: 'Reviews supported sales journal activity and related accounting entries.',
  },
  {
    moduleCode: 'SOA',
    name: 'Statement of Account',
    area: 'Sales',
    aliases: ['statements of account', 'customer account statement'],
    summary: 'Generates a summary of supported customer account balances and activity.',
  },
]);
