import { SystemGeneratedAuditLabel } from '../../../../common/utils/audit-user.util';
import type { AccountsPayableVoucherWithDetails } from '../types/accounts-payable-voucher-with-details.type';

const AccountsPayableVoucherReferenceType = 'APV';

export function mapAccountsPayableVoucher(voucher: AccountsPayableVoucherWithDetails, userNames: Map<number, string>) {
  const journalEntryHeader = voucher.journalEntryHeader;
  const journalEntries = voucher.journalEntries.map((entry) => ({
    id: entry.id.toString(),
    referenceType: entry.referenceType,
    referenceId: entry.referenceId.toString(),
    lineNumber: entry.lineNumber,
    accountId: entry.accountId.toString(),
    accountCode: entry.accountCodeSnapshot,
    accountTitle: entry.accountTitleSnapshot,
    currencyCode: entry.currencyCode,
    exchangeRate: Number(entry.exchangeRate),
    particulars: entry.particulars ?? null,
    debit: Number(entry.debit),
    credit: Number(entry.credit),
    vatType: entry.vatType ?? null,
    atcCode: entry.atcCode ?? null,
    partyCode: entry.partyCodeSnapshot ?? null,
    partyName: entry.partyNameSnapshot ?? null,
    responsibilityCenterId: entry.responsibilityCenterId?.toString() ?? null,
    responsibilityCenter: entry.responsibilityCenterSnapshot ?? null,
    refNo: entry.refNo ?? null,
  }));
  const journalEntryDetails = journalEntries.map((entry) => ({
    id: entry.id,
    lineNumber: entry.lineNumber,
    accountId: entry.accountId,
    accountCode: entry.accountCode,
    accountTitle: entry.accountTitle,
    debit: entry.debit,
    credit: entry.credit,
    vatType: entry.vatType,
    atcCode: entry.atcCode,
    partyCode: entry.partyCode,
    partyName: entry.partyName,
    responsibilityCenterId: entry.responsibilityCenterId,
    responsibilityCenter: entry.responsibilityCenter,
    refNo: entry.refNo,
  }));

  return {
    id: voucher.id.toString(),
    transactionNo: voucher.transactionNo,
    documentDate: toDateValue(voucher.documentDate),
    partyId: voucher.partyId?.toString() ?? null,
    partyCode: voucher.partyCodeSnapshot,
    partyName: voucher.partyNameSnapshot,
    address: voucher.addressSnapshot ?? null,
    contactPerson: voucher.contactPersonSnapshot ?? null,
    contactNo: voucher.contactNoSnapshot ?? null,
    projectCode: voucher.projectCode ?? null,
    projectName: voucher.projectName ?? null,
    currency: voucher.currencyCode,
    exchangeRate: Number(voucher.exchangeRate),
    amount: Number(voucher.amount),
    termId: voucher.termId?.toString() ?? null,
    terms: voucher.term?.name ?? null,
    dueDate: toDateValue(voucher.dueDate),
    referenceNo: voucher.referenceNo ?? null,
    creditAccountId: voucher.creditAccountId.toString(),
    creditAccountCode: voucher.creditAccount.accountCode,
    creditAccountTitle: voucher.creditAccount.accountTitle,
    payableType: voucher.payableType,
    remarks: voucher.remarks ?? null,
    status: voucher.status,
    details: voucher.details.map((detail) => ({
      id: detail.id.toString(),
      companyId: detail.companyId,
      branchUnitId: detail.branchUnitId,
      partyId: detail.partyId?.toString() ?? null,
      lineNumber: detail.lineNumber,
      expenseAccountId: detail.expenseAccountId.toString(),
      expenseAccountCode: detail.expenseAccountCodeSnapshot,
      expenseType: detail.expenseTypeSnapshot,
      currencyCode: detail.currencyCode,
      exchangeRate: Number(detail.exchangeRate),
      amount: Number(detail.amount),
      netAmount: Number(detail.netAmount),
      vat: detail.vat ?? null,
      vatPercent: Number(detail.vatPercent),
      vatAmount: Number(detail.vatAmount),
      ewt: detail.ewt ?? null,
      ewtPercent: Number(detail.ewtPercent),
      ewtAmount: Number(detail.ewtAmount),
      totalAmountDue: Number(detail.totalAmountDue),
      partyCode: detail.partyCodeSnapshot ?? null,
      partyName: detail.partyNameSnapshot ?? null,
      particulars: detail.particulars ?? null,
      responsibilityCenterId: detail.responsibilityCenterId?.toString() ?? null,
      responsibilityCenter: detail.responsibilityCenterSnapshot ?? null,
      referenceNo: detail.referenceNo ?? null,
    })),
    journalEntry: {
      header: {
        id: journalEntryHeader?.id.toString() ?? null,
        referenceType: journalEntryHeader?.referenceType ?? AccountsPayableVoucherReferenceType,
        referenceId: journalEntryHeader?.referenceId.toString() ?? voucher.id.toString(),
        referenceNo: journalEntryHeader?.referenceNo ?? voucher.referenceNo ?? null,
        transactionDate: toDateValue(journalEntryHeader?.transactionDate ?? voucher.documentDate),
        currencyCode: journalEntryHeader?.currencyCode ?? voucher.currencyCode,
        exchangeRate: Number(journalEntryHeader?.exchangeRate ?? voucher.exchangeRate),
        particulars: journalEntryHeader?.particulars ?? null,
        totalDebit: Number(journalEntryHeader?.totalDebit ?? 0),
        totalCredit: Number(journalEntryHeader?.totalCredit ?? 0),
        status: journalEntryHeader?.status ?? null,
      },
      details: journalEntryDetails,
    },
    journalEntries,
    createdBy: voucher.createdByUserId === null ? SystemGeneratedAuditLabel : (userNames.get(voucher.createdByUserId) ?? null),
    createdAt: voucher.createdAt.toISOString(),
    updatedBy: (voucher.updatedByUserId && userNames.get(voucher.updatedByUserId)) ?? null,
    updatedAt: voucher.updatedAt.toISOString(),
  };
}

function toDateValue(date: Date) {
  return date.toISOString().slice(0, 10);
}
