import { mapDisbursementVoucher } from './disbursement-voucher.mapper';
import type { DisbursementVoucherWithDetails } from '../types/disbursement-voucher-with-details.type';

describe('mapDisbursementVoucher', () => {
  it('maps voucher defaults and excludes generated credit lines from totals', () => {
    const voucher = {
      id: 42n,
      branchUnitId: 7,
      voucherNo: 'DV-0001',
      voucherDate: new Date('2026-09-01T00:00:00.000Z'),
      paymentDueDate: null,
      referenceNo: null,
      referenceModule: null,
      voucherReferenceNo: null,
      invoiceReferenceNo: null,
      paymentMethod: 'CASH',
      disbursementType: null,
      paymentDetails: null,
      attachments: null,
      partyId: null,
      partyCodeSnapshot: null,
      partyNameSnapshot: null,
      creditAccountId: null,
      projectCode: null,
      projectName: null,
      preparedBy: null,
      currencyCode: 'PHP',
      exchangeRate: 1,
      amount: 250,
      remarks: null,
      status: 'DRAFT',
      createdByUserId: null,
      createdAt: new Date('2026-09-01T00:00:00.000Z'),
      updatedByUserId: null,
      updatedAt: null,
      party: null,
      creditAccount: null,
      details: [
        {
          id: 1n,
          lineNumber: 1,
          accountId: null,
          accountCodeSnapshot: '6100',
          accountTitleSnapshot: 'Expense',
          particulars: null,
          remarks: null,
          debit: 250,
          credit: 0,
          grossAmount: 250,
          netAmount: 250,
          vatType: null,
          vatCode: null,
          vatPercent: 0,
          vatAmount: 0,
          ewtCode: null,
          ewtPercent: 0,
          ewtAmount: 0,
          disburseAmount: 250,
          partyId: null,
          partyCodeSnapshot: null,
          partyNameSnapshot: null,
          responsibilityCenterId: null,
          responsibilityCenterSnapshot: null,
          refId: null,
          checkDate: null,
          checkNo: null,
          checkStatus: null,
          account: null,
          party: null,
          responsibilityCenter: null,
        },
        {
          id: 2n,
          lineNumber: 2,
          accountId: null,
          accountCodeSnapshot: null,
          accountTitleSnapshot: 'Cash on Hand',
          particulars: null,
          remarks: null,
          debit: 0,
          credit: 250,
          grossAmount: 0,
          netAmount: 0,
          vatType: null,
          vatCode: null,
          vatPercent: 0,
          vatAmount: 0,
          ewtCode: null,
          ewtPercent: 0,
          ewtAmount: 0,
          disburseAmount: 0,
          partyId: null,
          partyCodeSnapshot: null,
          partyNameSnapshot: null,
          responsibilityCenterId: null,
          responsibilityCenterSnapshot: null,
          refId: null,
          checkDate: null,
          checkNo: null,
          checkStatus: null,
          account: null,
          party: null,
          responsibilityCenter: null,
        },
      ],
      journalEntries: [],
    } as unknown as DisbursementVoucherWithDetails;

    const result = mapDisbursementVoucher(voucher, new Map());

    expect(result.dueDate).toBe('2026-09-01');
    expect(result.paymentDetails).toEqual(expect.objectContaining({ bankName: '' }));
    expect(result.attachments).toEqual([]);
    expect(result.amount).toBe(250);
    expect(result.disburseAmount).toBe(250);
  });
});
